version: 0.0
os: linux
files:
  - source: /codedeploy-demo-1.0.0.jar
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "codedeploy-demo-1.0.0.jar"
    owner: ec2-user
    group: ec2-user
    mode: 664
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ec2-user
  ValidateService:
    - location: scripts/validation.sh
      timeout: 30
      runas: ec2-user